name: CI

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Free disk space
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install build-essential clang flex g++ gawk gcc-multilib gettext \
            git libncurses5-dev libssl-dev python3-distutils rsync unzip zlib1g-dev

      - name: Checkout
        uses: actions/checkout@v3

      - name: Hook the openwrt_core URL for opkg
        run: |
          OWNER="${GITHUB_REPOSITORY%%/*}"
          REPO="${GITHUB_REPOSITORY#*/}"
          TIME="$(curl "https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}" | jq -r .created_at)"

          echo "ci-$(date -d "${TIME}" -u +'%Y%m%d-%H%M%S')-${GITHUB_SHA:0:8}" >version
          sed -i "s|%U/targets/%S/packages|https://${OWNER}.github.io/${REPO}/${GITHUB_REF_NAME}/%R|" include/feeds.mk

      - name: Update and install feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Configure
        run: |
          cat <<EOF | sed -E 's/^  //' >.config
            CONFIG_TARGET_ipq50xx=y
            CONFIG_TARGET_ipq50xx_arm=y
            CONFIG_TARGET_MULTI_PROFILE=y
            CONFIG_TARGET_ALL_PROFILES=y
            CONFIG_TARGET_PER_DEVICE_ROOTFS=y

            CONFIG_IB=y
            # CONFIG_IB_STANDALONE is not set
            CONFIG_SDK=y
            CONFIG_MAKE_TOOLCHAIN=y

            CONFIG_ALL_NONSHARED=y
            CONFIG_REPRODUCIBLE_DEBUG_INFO=y

            CONFIG_PACKAGE_luci=y
          EOF
          make defconfig

      - name: Download
        run: |
          make -j16 download

      - name: Build tools
        run: |
          make -j$(nproc) tools/install

      - name: Build toolchain
        run: |
          make -j$(nproc) toolchain/install

      - name: Build all
        run: |
          make -j$(nproc) IGNORE_ERRORS=1

      - name: Upload bin to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: bin-ipq50xx-arm
          path: bin/targets/ipq50xx/arm/*

      - name: Upload dl to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dl
          path: dl/*
